version: "3.9"
services:
  # PostgreSQL service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: addressbook
    ports:
      - "5432:5432"
    volumes:
      - addressbook-db:/var/lib/postgresql/data

  # Node.js application service
  addressbook:
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: addressbook
      DB_PORT: 5432
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: npm start

volumes:
  addressbook-db:
